/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoPI;

/**
 *
 * @author Camilly
 */
public class TelaParaCincoEngrenagensDesbloqueadas extends javax.swing.JFrame {

    /**
     * Creates new form TelaParaCincoEngrenagensDesbloqueadas
     */
    public TelaParaCincoEngrenagensDesbloqueadas() { //Tela que deverá aparecer quando o jogador acertar AS CINCO PERGUNTAS!!

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoContinuarCincoEngrenagens = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1040, 545));
        setMinimumSize(new java.awt.Dimension(1040, 530));
        setPreferredSize(new java.awt.Dimension(1040, 545));
        setResizable(false);
        getContentPane().setLayout(null);

        botaoContinuarCincoEngrenagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoContinuar.png"))); // NOI18N
        botaoContinuarCincoEngrenagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoContinuarCincoEngrenagensMouseClicked(evt);
            }
        });
        getContentPane().add(botaoContinuarCincoEngrenagens);
        botaoContinuarCincoEngrenagens.setBounds(470, 410, 120, 40);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 460, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/TelaParaCincoEngrenagensDesbloqueadas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContinuarCincoEngrenagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoContinuarCincoEngrenagensMouseClicked
        Telavitoria botaoContinuar = new Telavitoria();
            botaoContinuar.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botaoContinuarCincoEngrenagensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaParaCincoEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaParaCincoEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaParaCincoEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParaCincoEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaParaCincoEngrenagensDesbloqueadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoContinuarCincoEngrenagens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
