/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoPI;

import javax.swing.JOptionPane;

/**
 *
 * @author Camilly
 */
public class TelaParaQuatroEngrenagensDesbloqueadas extends javax.swing.JFrame {

    /**
     * Creates new form TelaParaQuatroEngrenagemDesbloqueada
     */
    public TelaParaQuatroEngrenagensDesbloqueadas() {//Tela que deverá aparecer quando o jogador acertar QUATRO PERGUNTAS!!
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoContinuarQuatroEngrenagens = new javax.swing.JLabel();
        botaoDesistirQuatroEngrenagens = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1060, 530));
        setMinimumSize(new java.awt.Dimension(1000, 530));
        setPreferredSize(new java.awt.Dimension(1050, 545));
        setResizable(false);
        getContentPane().setLayout(null);

        botaoContinuarQuatroEngrenagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoContinuar.png"))); // NOI18N
        botaoContinuarQuatroEngrenagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoContinuarQuatroEngrenagensMouseClicked(evt);
            }
        });
        getContentPane().add(botaoContinuarQuatroEngrenagens);
        botaoContinuarQuatroEngrenagens.setBounds(350, 430, 120, 40);

        botaoDesistirQuatroEngrenagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoDesistir.png"))); // NOI18N
        botaoDesistirQuatroEngrenagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDesistirQuatroEngrenagensMouseClicked(evt);
            }
        });
        getContentPane().add(botaoDesistirQuatroEngrenagens);
        botaoDesistirQuatroEngrenagens.setBounds(550, 430, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/TelaParaQuatroEngrenagensDesbloqueadas.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContinuarQuatroEngrenagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoContinuarQuatroEngrenagensMouseClicked
        Telaquiz botaoContinuar = new Telaquiz();
            botaoContinuar.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_botaoContinuarQuatroEngrenagensMouseClicked

    private void botaoDesistirQuatroEngrenagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDesistirQuatroEngrenagensMouseClicked
        JOptionPane.showMessageDialog (null, "Não desista. Tente Novamente!");
         System.exit(0);
    }//GEN-LAST:event_botaoDesistirQuatroEngrenagensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaParaQuatroEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaParaQuatroEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaParaQuatroEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParaQuatroEngrenagensDesbloqueadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaParaQuatroEngrenagensDesbloqueadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoContinuarQuatroEngrenagens;
    private javax.swing.JLabel botaoDesistirQuatroEngrenagens;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
