/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoPI;
import javax.swing.JOptionPane;
/**
 *
 * @author Camilly
 */
public class Telavitoria extends javax.swing.JFrame {

    /**
     * Creates new form telaVitória
     */
    public Telavitoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoReiniciar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoSair1 = new javax.swing.JLabel();
        Telavitoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1040, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoReiniciar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoReiniciar.png"))); // NOI18N
        botaoReiniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoReiniciar1MouseClicked(evt);
            }
        });
        getContentPane().add(botaoReiniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/medalha.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -40, 554, 315));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        botaoSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoSair.png"))); // NOI18N
        botaoSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSair1MouseClicked(evt);
            }
        });
        getContentPane().add(botaoSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 120, 40));

        Telavitoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/telavitoria.png"))); // NOI18N
        Telavitoria.setText("jLabel2");
        getContentPane().add(Telavitoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1050, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoReiniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoReiniciar1MouseClicked
         Telainicial botaoReiniciar = new Telainicial();
           botaoReiniciar.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_botaoReiniciar1MouseClicked

    private void botaoSair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSair1MouseClicked
         System.exit(0);
    }//GEN-LAST:event_botaoSair1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telavitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telavitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telavitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telavitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telavitoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Telavitoria;
    private javax.swing.JLabel botaoReiniciar1;
    private javax.swing.JLabel botaoSair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
