/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoPI;

/**
 *
 * @author Camilly
 */
public class Telapresentacaodojogo extends javax.swing.JFrame {

    Object set;

    /**
     * Creates new form telabinicio
     */
    public Telapresentacaodojogo() { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        botaoProximo = new javax.swing.JLabel();
        Telapresentacaojogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1040, 523));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1551, 88, 32));

        botaoProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/botaoProximo.png"))); // NOI18N
        botaoProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoProximoMouseClicked(evt);
            }
        });
        getContentPane().add(botaoProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 120, 40));

        Telapresentacaojogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoPI/imagens/imagens/tela apresentação do jogo(com texto).png"))); // NOI18N
        getContentPane().add(Telapresentacaojogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 490));

        setSize(new java.awt.Dimension(1064, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProximoMouseClicked
          TelaMaquinadoTempo botaoProximo = new TelaMaquinadoTempo();
           botaoProximo.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_botaoProximoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telapresentacaodojogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telapresentacaodojogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telapresentacaodojogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telapresentacaodojogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telapresentacaodojogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Telapresentacaojogo;
    private javax.swing.JLabel botaoProximo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
